<!-- Generated by ::xowiki::ADP_Generator on Tue Nov 27 20:12:58 CET 2012 -->
<!-- The following DIV is needed for overlib to function! -->
  <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>	
<div class='xowiki-content'>

@top_includelets;noquote@
<h1>@title@</h1>
@content;noquote@

</div> <!-- class='xowiki-content' -->
